name: DGlabMC
version: '${version}'
main: shirohaNya.dglabmc.DGlabMC
api-version: '1.19'
commands:
  dglab:
    description: 在mc中控制郊狼喵
    usage: /dglab ...
permissions:
################################################################
  dglab.*:
    default: op
    children:
      dglab.reload: true
      dglab.getqrcode: true
      dglab.info: true
      dglab.bind: true
      dglab.ctrl: true
      dglab.game: true
      dglab.others: true
      dglab.send: true
      dglab.shock: true
      dglab.server: true
################################################################
  dglab.reload:
    default: op
  dglab.getqrcode:
    default: true
################################################################
  dglab.info:
    default: true
    children:
      dglab.info.others: false
  dglab.info.others:
    default: op
################################################################
  dglab.bind:
    default: true
    children:
      dglab.bind.list: false
      dglab.bind.others: false
  dglab.bind.list:
    default: op
  dglab.bind.others:
    default: op
################################################################
  dglab.ctrl:
    default: true
    children:
      dglab.ctrl.pulse: true
      dglab.ctrl.strength: true
      dglab.ctrl.others: false
  dglab.ctrl.pulse:
    default: op
  dglab.ctrl.strength:
    default: op
  dglab.ctrl.others:
    default: op
################################################################
  dglab.game:
    default: true
    children:
      dglab.game.enable: true
      dglab.game.disable: true
      dglab.game.list: false
      dglab.game.others: false
  dglab.game.enable:
    default: true
  dglab.game.disable:
    default: true
  dglab.game.list:
    default: op
  dglab.game.others:
    default: op
################################################################
  dglab.send:
    default: op
    children:
      dglab.send.dgjson: true
      dglab.send.msg: true
  dglab.send.dgjson:
    default: op
  dglab.send.msg:
    default: op
################################################################
  dglab.server:
    default: op
    children:
      dglab.server.run: true
      dglab.server.stop: true
  dglab.server.run:
    default: op
  dglab.server.stop:
    default: op
################################################################
  dglab.shock:
    default: true
    children:
      dglab.shock.others: false
  dglab.shock.others:
    default: op
################################################################
  dglab.list:
    default: op
    children:
      dglab.game.list: true
################################################################
  dglab.others:
    default: op
    children:
      dglab.info.others: true
      dglab.bind.others: true
      dglab.ctrl.others: true
      dglab.game.others: true
      dglab.shock.others: true
################################################################


