ip: "127.0.0.1"
port: 9999
autoRunServer: true
mcUUID : null
scripts:
  - script1:
      default: false
      time: 5
      replace: true
  - script2:
      default: false

################################
#           Example            #
# - script2:                   #
#     default: false           #
#     setting1: value1         #
#     setting2: value2         #
#     ...                      #
################################