name: DGlabMC
version: '1.1.0'
main: shirohaNya.dglabmc.DGlabMC
api-version: '1.19'
commands:
  dglab:
    description: 在mc中控制郊狼喵
    usage: /dglab ...
permissions:
################################################################
  dglab.*:
    default: op
    children:
      dglab.getQRcode: true
      dglab.reload: true
      dglab.getAddress: true
      dglab.info: true
      dglab.bind: true
      dglab.ctrl: true
      dglab.script: true
      dglab.others: true
      dglab.send: true
      dglab.shock: true
      dglab.server: true
      dglab.bossbar: true
################################################################
  dglab.reload:
    default: op
  dglab.getQRcode:
    default: true
  dglab.getAddress:
    default: true
  dglab.bossbar:
    default: true
################################################################
  dglab.info:
    default: true
    children:
      dglab.info.others: false
  dglab.info.others:
    default: op
################################################################
  dglab.bind:
    default: true
    children:
      dglab.bind.list: false
      dglab.bind.others: false
  dglab.bind.list:
    default: op
  dglab.bind.others:
    default: op
################################################################
  dglab.ctrl:
    default: true
    children:
      dglab.ctrl.pulse: true
      dglab.ctrl.strength: true
      dglab.ctrl.others: false
  dglab.ctrl.pulse:
    default: op
  dglab.ctrl.strength:
    default: op
  dglab.ctrl.others:
    default: op
################################################################
  dglab.script:
    default: true
    children:
      dglab.script.enable: true
      dglab.script.disable: true
      dglab.script.list: false
      dglab.script.others: false
  dglab.script.enable:
    default: true
  dglab.script.disable:
    default: true
  dglab.script.list:
    default: op
  dglab.script.others:
    default: op
################################################################
  dglab.send:
    default: op
    children:
      dglab.send.dgjson: true
      dglab.send.msg: true
  dglab.send.dgjson:
    default: op
  dglab.send.msg:
    default: op
################################################################
  dglab.server:
    default: op
    children:
      dglab.server.run: true
      dglab.server.stop: true
  dglab.server.run:
    default: op
  dglab.server.stop:
    default: op
################################################################
  dglab.shock:
    default: true
    children:
      dglab.shock.others: false
  dglab.shock.others:
    default: op
################################################################
  dglab.list:
    default: true
    children:
      dglab.script.list: true
################################################################
  dglab.others:
    default: op
    children:
      dglab.info.others: true
      dglab.bind.others: true
      dglab.ctrl.others: true
      dglab.script.others: true
      dglab.shock.others: true
################################################################


